version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"   # external:internal
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:80"   # external:internal
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123"
    ports:
      - "1433:1433"
