version: '3.8'

services:
  backend:
    build: ./backend/SanaVitaAPI
    container_name: sanavita-backend
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=SanaVita;User Id=sa;Password=YourStrong(!)Password;"
    networks:
      - sanavita-net

  frontend:
    build: ./frontend
    container_name: sanavita-frontend
    ports:
      - "5173:80"  # ou 3000:80 se for React puro
    networks:
      - sanavita-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sanavita-sql
    environment:
      SA_PASSWORD: "YourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./database:/var/opt/mssql/backup
    networks:
      - sanavita-net

networks:
  sanavita-net:
    driver: bridge
