version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=SanaVitaDb;User Id=sa;Password=sa;"
    depends_on:
      - sqlserver

  frontend:
    build: ./frontend
    ports:
      - "5173:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "sa"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
